# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=18, verbose_name='组名')),
                ('gmark', models.CharField(max_length=18, unique=True, verbose_name='组标识')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=18, unique=True, verbose_name='权限标识')),
                ('limit_description', models.CharField(max_length=18, verbose_name='权限描述')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=24, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=24, null=True, verbose_name='密码')),
                ('avatar', models.CharField(max_length=200, verbose_name='头像')),
                ('is_active', models.BooleanField(default=1, verbose_name='启用壮态')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证')),
                ('name', models.CharField(max_length=18, verbose_name='姓名')),
                ('picture', models.CharField(max_length=200, verbose_name='图片')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(max_length=48, verbose_name='联系方式')),
                ('ulimits', models.ManyToManyField(to='user.Limits')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='glimits',
            field=models.ManyToManyField(to='user.Limits'),
        ),
        migrations.AddField(
            model_name='groups',
            name='gusers',
            field=models.ManyToManyField(to='user.Users'),
        ),
    ]
