# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='关注时间')),
                ('is_cancel', models.BooleanField(default=0, verbose_name='是否取消')),
                ('attentions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention', to='users.Users', verbose_name='被关注人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.Users', verbose_name='关注人')),
            ],
        ),
    ]
