# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_orders_number', models.CharField(max_length=18, verbose_name='订单单号')),
                ('service_number', models.CharField(max_length=18, verbose_name='服务单号')),
                ('provider', models.CharField(max_length=24, verbose_name='服务提供方')),
                ('demand', models.CharField(max_length=24, verbose_name='服务需求方')),
                ('method', models.CharField(max_length=9, verbose_name='类别')),
                ('title', models.CharField(max_length=18, verbose_name='标题')),
                ('details', models.CharField(max_length=400, verbose_name='详细介绍')),
                ('appoint_time', models.CharField(max_length=100, verbose_name='预约时间')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('area', models.CharField(max_length=100, verbose_name='服务地点')),
                ('price', models.FloatField(verbose_name='服务价格')),
                ('unit', models.CharField(max_length=18, verbose_name='价格单位')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_complate', models.BooleanField(default=0, verbose_name='是否完成')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=18, verbose_name='服务单号')),
                ('role', models.BooleanField(choices=[(0, '需求方'), (1, '提供方')], verbose_name='角色')),
                ('method', models.IntegerField(choices=[(0, '到店服务'), (1, '上门服务'), (2, '场所约见'), (3, '电话服务'), (4, '视频服务'), (5, '其他方式')], verbose_name='服务方式')),
                ('title', models.CharField(max_length=18, verbose_name='标题')),
                ('details', models.CharField(max_length=400, verbose_name='详细介绍')),
                ('appoint_time', models.CharField(max_length=100, verbose_name='预约时间')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('area', models.CharField(max_length=100, verbose_name='服务地点')),
                ('price', models.FloatField(verbose_name='服务价格')),
                ('unit', models.IntegerField(choices=[(0, '次'), (1, '小时'), (2, '天'), (3, '件'), (4, '自定义')], verbose_name='价格单位')),
                ('is_release', models.BooleanField(default=1, verbose_name='是否发布')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=18, verbose_name='状态名')),
                ('smark', models.CharField(max_length=18, unique=True, verbose_name='壮态标记')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='states',
            field=models.ManyToManyField(to='release.States'),
        ),
    ]
