# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=18, unique=True, verbose_name='权限标识')),
                ('limit_description', models.CharField(max_length=18, verbose_name='权限描述')),
            ],
        ),
    ]
