# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400, verbose_name='评论内容')),
                ('fraction', models.IntegerField(verbose_name='分数')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.ServiceOrders', verbose_name='评论订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='评论者')),
            ],
        ),
    ]
